### ISSUE TITLE
Intake motor on alphabot

### ISSUE THREAD

**Issue by caseyjbrotherton** [frc6377/crescendo_2024#26]

**Comment by caseyjbrotherton** [comment]
Alphabot has a sparkmax and neo installed to control an intake.

Code needs to be added to the alphabot branch to control this motor.

- CAN id needs to be found
- PID control is probably not necessary ( Set the output to .75 to start? )
- Assign to a button that the driver asks for.

**Comment by ModBoyex** [comment]
And I helped.
