### ISSUE TITLE
Audit CTRE code to ensure it includes proper logging

### ISSUE THREAD

**Issue by caseyjbrotherton** [frc6377/crescendo_2024#47]
We should be logging the following for all motors at all times:
* Actual motor output
* Desired speed of mechanism
* Actual speed of mechanism

**Comment by caseyjbrotherton** [comment]
If the logging doesn't exist, we should add to the template to make sure that it is logged as well

**Comment by ModBoyex** [comment]
Based on what be and Cacey found, getting the actual angle of the motors is much more inconvenient with our new CTRE "Magic Button" way of making swerve. The actual motors are under multiple layer of code, and are not easy to log
