### ISSUE TITLE
What should be in .gitignore?

### ISSUE THREAD

**Issue by azvanderpas** [frc6377/crescendo_2024#6]
This is scary to me.  I don't think we would ever put a txt in deploy, but any file that went to the robot, I would want to make sure went to github.

_Originally posted by @caseyjbrotherton in https://github.com/frc6377/crescendo_2024/pull/1#discussion_r1445456243_

**Comment by caseyjbrotherton** [comment]
Waiting until we decide whether advantagekit logs the same information.

**Comment by caseyjbrotherton** [comment]
AdvantageKit creates a buildconstants file.

That is included in the jar file that is put on the robot.

It is available in the jar, but probably easier to have the text files as well.  We can keep both fir right now:

`casey@obsidian:~/Documents/code/crescendo_2024$ jar tvf ./build/libs/crescendo_2024.jar | grep BuildCon
   810 Sun Jan 14 14:29:40 CST 2024 frc/robot/BuildConstants.class
   756 Sun Jan 14 14:29:40 CST 2024 frc/robot/BuildConstants.java
casey@obsidian:~/Documents/code/crescendo_2024$ cat ./src/main/java/frc/robot/BuildConstants.java
package frc.robot;

/**
 * Automatically generated file containing build version information.
 */
public final class BuildConstants {
  public static final String MAVEN_GROUP = "";
  public static final String MAVEN_NAME = "crescendo_2024";
  public static final String VERSION = "unspecified";
  public static final int GIT_REVISION = 57;
  public static final String GIT_SHA = "8711134c6dfed7b178c6ae55abd6f2b3beeaf3bd";
  public static final String GIT_DATE = "2024-01-14 14:23:41 CST";
  public static final String GIT_BRANCH = "Install-Advantage-Kit";
  public static final String BUILD_DATE = "2024-01-14 14:29:41 CST";
  public static final long BUILD_UNIX_TIME = 1705264181243L;
  public static final int DIRTY = 0;

  private BuildConstants(){}
}
`
