### ISSUE TITLE
Test auto paths with Alphabot

### ISSUE THREAD

**Issue by lohengrin332** [frc6377/crescendo_2024#64]
Alphabot has sat idle for a week. We should take the opportunity to validate the autons we created on a real bot, with the understanding that they won't work exactly correctly because they were created for a different sized drivebase.

**Comment by caseyjbrotherton** [comment]
INitial path work was done.

Odometry down to 1 inch per 3 meters error.  Moving to done.  Will open specific tasks when they come up.
