### ISSUE TITLE
Build scouting app in powerbuilder

### ISSUE THREAD

**Issue by caseyjbrotherton** [frc6377/crescendo_2024#67]

**Comment by caseyjbrotherton** [comment]
@ModBoyex @Asher123456789 please fill in the description of the steps in this task.  Feel free to break it down into multiple parts if that makes it easier

**Comment by HowdyFromATX** [comment]
Scott is updating the underlying database structure today (1/28) based on https://docs.google.com/document/d/16pyJMiUzxKP-LBEwKfJ6FeD7taQMrUe_jK-Kw5Q2cD4/edit#heading=h.w6nc2fqumgll

**Comment by caseyjbrotherton** [comment]
Closing, work done by scott
