### ISSUE TITLE
tracking git branch on roborio

### ISSUE THREAD

**Issue by caseyjbrotherton** [frc6377/crescendo_2024#7]

**Comment by Josh-Westbrook** [comment]
validated/ran test

**Comment by azvanderpas** [comment]
Lets evaluate if AdvantageKit's Build Constants method makes our current method obsolete.

**Comment by caseyjbrotherton** [comment]
We can use the build constants for this.  We will close this issue, and create another low priority to remove the build.gradle items to save git hash
