### ISSUE TITLE
Code for prototyping shooters

### ISSUE THREAD

**Issue by ModBoyex** [frc6377/crescendo_2024#8]
The same code for making both the vertical and horizontal shooter prototypes testable.

**Comment by rishik4** [comment]
Working on changing setpoint value with controller triggers. - Rishik B.

**Comment by rishik4** [comment]
Adding being able to view flywheel speeds and set PID values on the dashboard. - Rishik B.

**Comment by ModBoyex** [comment]
Only works with setting to percent at the moment, but trying to find a fix.

**Comment by ModBoyex** [comment]
Going to merge Advantage kit to this branch

**Comment by ModBoyex** [comment]
This branch is working and is in use for prototypes
