### ISSUE TITLE
Line up to the amp using the odometry of the robot

### ISSUE THREAD

**Issue by caseyjbrotherton** [frc6377/crescendo_2024#83]
Assuming that we have a consistent robot position for the entire match, it would be helpful to be able to "move to in front of amp"

There will be a couple of "line up" issues.  This is the highest priority of them.

Required:
Ability to be cancelled by driver/operator action
Ability to indicate when lock is possible. ( Shuffleboard maybe? )
Ability to indicate when lock is on ( shuffleboard and rumble? )
position the amp mechanism in front of the amp

Nice to have:
Avoid known field elements
Ability to detect a collision and do something. ( cancel lock, maybe? )

Non goal:
Avoiding other robots ( The assumption will be that the driver/operator will not start a lock when there is another robot in the way )

**Comment by caseyjbrotherton** [comment]
@zbrotherton you were working on this today?

**Comment by HowdyFromATX** [comment]
We expect the driver will get the robot across the field and within ~5-8 feet of the amp before engaging - think of this as "assisted parking"

Depending on how the amp scoring mechanism works - a nice to have would be to automatically score the amp once the robot knows it is in the proper position/distance.

**Comment by caseyjbrotherton** [comment]
Fixed by #147
